# Generated by Django 5.0.2 on 2024-04-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myus", "0006_alter_extraguessgrant_id_alter_guess_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guessresponse",
            name="response",
            field=models.CharField(max_length=500),
        ),
    ]
