# Generated by Django 5.0.2 on 2024-04-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myus", "0007_alter_guessresponse_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="guess",
            name="counts_as_guess",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guess",
            name="response",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
