# Generated by Django 5.0.6 on 2024-10-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myus", "0008_guess_counts_as_guess_guess_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="answer_response",
            field=models.CharField(
                default="",
                help_text='Response to a correct answer. Default is "You have solved this puzzle!". Basic html and images allowed.',
                max_length=500,
            ),
        ),
    ]
