# Generated by Django 5.0.6 on 2024-10-30 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myus", "0009_puzzle_answer_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="hunt",
            name="leaderboard_style",
            field=models.CharField(
                choices=[
                    (
                        "DEF",
                        "Default (ordered by score, solve count, and last solve time)",
                    ),
                    ("HID", "Hidden (not displayed publicly)"),
                    ("SPD", "Speedrun (ordered by score and time to solve)"),
                ],
                default="DEF",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="hunt",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="(Not implemented) End date of the hunt. If empty, the hunt will always be open.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hunt",
            name="member_limit",
            field=models.IntegerField(
                default=0,
                help_text="(Not implemented) The maximum number of members allowed per team; 0 means unlimited",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="hunt",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="(Not implemented) Start time of the hunt. If empty, the hunt will never begin. For indefinitely open hunts, you can just set it to any time in the past.",
                null=True,
            ),
        ),
    ]
