# Generated by Django 5.0.2 on 2024-10-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myus", "0010_hunt_leaderboard_style_alter_hunt_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="answer_response",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Response to a correct answer. Default is "You have solved this puzzle!". Basic html and images allowed.',
                max_length=500,
            ),
        ),
    ]
