# Generated by Django 5.0.2 on 2024-11-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("myus", "0012_hunt_solution_style_puzzle_solution_url"),
        ("myus", "0013_alter_puzzle_solution_url"),
        ("myus", "0014_alter_puzzle_solution_url"),
    ]

    dependencies = [
        ("myus", "0011_alter_puzzle_answer_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="hunt",
            name="solution_style",
            field=models.CharField(
                choices=[
                    ("VIS", "Solutions are always visible"),
                    ("HID", "Solutions are always hidden"),
                    ("SOL", "Solution displayed after puzzle is solved"),
                ],
                default="HID",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="solution_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL of solution.",
                max_length=500,
                verbose_name="Solution URL",
            ),
        ),
    ]
