# Generated by Django 5.1.3 on 2024-12-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myus",
            "0012_hunt_solution_style_puzzle_solution_url_squashed_0014_alter_puzzle_solution_url",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hunt",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="If true, only organizers can view the hunt and its puzzles. Defaults to false.",
            ),
        ),
    ]
